(window.webpackJsonp=window.webpackJsonp||[]).push([[34],{173:function(e,t,n){"use strict";n.r(t),n.d(t,"frontMatter",(function(){return o})),n.d(t,"metadata",(function(){return r})),n.d(t,"rightToc",(function(){return l})),n.d(t,"default",(function(){return b}));var a=n(1),i=n(9),c=(n(0),n(231)),o={title:"Exceptions (Java)",description:"The different kinds of exceptions in Java and some best practices for using them",last_modified:new Date("2022-01-31T10:44:35.260Z"),sidebar_label:"Exceptions"},r={id:"java/exceptions",title:"Exceptions (Java)",description:"The different kinds of exceptions in Java and some best practices for using them",source:"@site/docs\\java\\exceptions.md",permalink:"/interview-prep/java/exceptions",sidebar_label:"Exceptions",sidebar:"docs",previous:{title:"Equals (Java)",permalink:"/interview-prep/java/equals"},next:{title:"Generics (Java)",permalink:"/interview-prep/java/generics"}},l=[{value:"Basics",id:"basics",children:[]},{value:"Checked versus unchecked exceptions",id:"checked-versus-unchecked-exceptions",children:[]},{value:"Throwing and the <code>throws</code> declaration",id:"throwing-and-the-throws-declaration",children:[]},{value:"Catching exceptions",id:"catching-exceptions",children:[]},{value:"Cleaning up using try-with-resources",id:"cleaning-up-using-try-with-resources",children:[]},{value:"Cleaning up using <code>finally</code>",id:"cleaning-up-using-finally",children:[]},{value:"Rethrowing and chaining",id:"rethrowing-and-chaining",children:[]},{value:"Dealing with <code>NullPointerException</code>",id:"dealing-with-nullpointerexception",children:[]},{value:"Turning checked exceptions into unchecked exceptions",id:"turning-checked-exceptions-into-unchecked-exceptions",children:[]},{value:"Resources",id:"resources",children:[]}],s={rightToc:l};function b(e){var t=e.components,n=Object(i.a)(e,["components"]);return Object(c.b)("wrapper",Object(a.a)({},s,n,{components:t,mdxType:"MDXLayout"}),Object(c.b)("p",null,"The different kinds of exceptions in Java and some best practices for using them"),Object(c.b)("h2",{id:"basics"},"Basics"),Object(c.b)("p",null,"Exception handling:"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"A method can throw an exception indicating that something is wrong"),Object(c.b)("li",{parentName:"ul"},"Exceptions automatically bubble up the call chain until they are handled (or, if they are not handled, they end up terminating the current thread)",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"Great benefit when comparing to error codes which must be manually passed up the chain if needed"))),Object(c.b)("li",{parentName:"ul"},"Typically, exceptions include a stack trace, indicating where the exception occurred in the code and what the call chain looked like at the time")),Object(c.b)("p",null,"Hierarchy of exception classes in Java:"),Object(c.b)("p",null,Object(c.b)("img",Object(a.a)({parentName:"p"},{src:"/img/from-notes/java/exceptions/shyamzzp.jpeg",alt:"Exception hierarchy"}))),Object(c.b)("p",null,"Classes:"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},Object(c.b)("inlineCode",{parentName:"li"},"Throwable"),": ",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"Common superclass for all Java exceptions"))),Object(c.b)("li",{parentName:"ul"},Object(c.b)("inlineCode",{parentName:"li"},"Error"),": ",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"Exceptions defined by the Java language that are thrown when something really bad happens that the code can normally not recover from by itself"),Object(c.b)("li",{parentName:"ul"},"All ",Object(c.b)("em",{parentName:"li"},"unchecked")," (see below)"),Object(c.b)("li",{parentName:"ul"},"Example: ",Object(c.b)("inlineCode",{parentName:"li"},"OutOfMemoryError"),", which occurs when Java is unable to allocate space to an object because there is no more memory available and garbage collection does not help. If you run into that one, the best you can generally do is exit the program."))),Object(c.b)("li",{parentName:"ul"},Object(c.b)("inlineCode",{parentName:"li"},"Exception"),":",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"All user-defined exceptions are subclasses of this one"),Object(c.b)("li",{parentName:"ul"},"Exceptions deriving directly from this one are ",Object(c.b)("em",{parentName:"li"},"checked")," (see below) exceptions"))),Object(c.b)("li",{parentName:"ul"},Object(c.b)("inlineCode",{parentName:"li"},"RuntimeException")," :",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"User-defined exceptions that are subclasses of this one are ",Object(c.b)("em",{parentName:"li"},"unchecked")," (see below) exceptions ")))),Object(c.b)("h2",{id:"checked-versus-unchecked-exceptions"},"Checked versus unchecked exceptions"),Object(c.b)("p",null,"Basic idea:"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"Checked: Checked by compiler",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"If your code can possibly throw a checked exception, the Java compiler requires you to either catch the exception or use a ",Object(c.b)("inlineCode",{parentName:"li"},"throws")," declaration to indicate that your code can throw the exception"))),Object(c.b)("li",{parentName:"ul"},"Unchecked: Not checked by compiler")),Object(c.b)("p",null,"Intention of this design:"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"Use checked exceptions when there is a reasonable way of recovering from the failure during the execution of the program",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"Example: a call to open a file and write to it, which can fail if the file does not exist. A reasonable way of recovering from this is trying a different filename."),Object(c.b)("li",{parentName:"ul"},"When using checked exceptions, the compiler forces you to to decide what to do in case such an exception occurs. This prevents you from forgetting that this kind of failure can actually happen."))),Object(c.b)("li",{parentName:"ul"},"Use unchecked exceptions for errors that the program cannot reasonably recover from",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"Example: exceptions indicating programming errors, like ",Object(c.b)("inlineCode",{parentName:"li"},"NullPointerException"))))),Object(c.b)("p",null,"Alternative school of thought:"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"Use checked exceptions if there is a reasonable way of recovering from the failure during the execution of the program ",Object(c.b)("strong",{parentName:"li"},"and")," the possibility for failure is unavoidable (an example is a missing file: even if you checked for its existence before, the file can still have disappeared in the meantime)",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"If the possibility for failure is unavoidable, it makes sense to force the caller to deal with the possible failure"))),Object(c.b)("li",{parentName:"ul"},"Use unchecked exceptions in all other cases."),Object(c.b)("li",{parentName:"ul"},"Evaluate these conditions at every level in the call chain.")),Object(c.b)("p",null,"Yet another different (and popular school of thought):"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"Always use unchecked exceptions. "),Object(c.b)("li",{parentName:"ul"},"Never use checked exceptions (unless you are maybe writing a very critical library)."),Object(c.b)("li",{parentName:"ul"},"This is advertised in, amongst others, the ",Object(c.b)("em",{parentName:"li"},"Clean Code")," book by Robert C. Martin"),Object(c.b)("li",{parentName:"ul"},"Reason: drawbacks of checked exceptions",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"If you throw a checked exception from your code and the appropriate handler sits three levels higher in the call chain, you must declare the exception on every method in between"),Object(c.b)("li",{parentName:"ul"},"This means that a single change to a small method somewhere deep in the program can require the signature of several higher-level methods to change, breaking encapsulation and coupling the handler of the exception to the code that generates it"),Object(c.b)("li",{parentName:"ul"},"This actually negates a large benefit of exceptions, which is that you can decouple the code detecting a failure from the code handling the failure")))),Object(c.b)("h2",{id:"throwing-and-the-throws-declaration"},"Throwing and the ",Object(c.b)("inlineCode",{parentName:"h2"},"throws")," declaration"),Object(c.b)("p",null,"Throwing unchecked exception:"),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),'public static boolean isNumberBetween(int number, int lower, int upper) {\n    if (lower > upper) {\n        throw new IllegalArgumentException(\n            "Lower bound cannot be higher than upper bound");\n    }\n    \n    // ...\n}\n')),Object(c.b)("p",null,"If code can throw a checked exception, a ",Object(c.b)("inlineCode",{parentName:"p"},"throws")," clause is mandatory!"),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),"public void write(String text, String filePath) throws IOException {\n    // potentially throws checked IOException\n    Files.write(Paths.get(filePath), text.getBytes());\n}\n")),Object(c.b)("p",null,"Throws and inheritance:"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"If you override a method, you cannot throw more checked exceptions than the original ",Object(c.b)("inlineCode",{parentName:"li"},"throws")," clause specifies. Otherwise, you would break the contract of the method."),Object(c.b)("li",{parentName:"ul"},"If a method does not have a ",Object(c.b)("inlineCode",{parentName:"li"},"throws")," clause, a method overriding it cannot throw any checked exceptions"),Object(c.b)("li",{parentName:"ul"},"Note that you can perfectly override a method declaring checked exceptions with a method not throwing any exceptions at all")),Object(c.b)("h2",{id:"catching-exceptions"},"Catching exceptions"),Object(c.b)("p",null,"Simple try-catch block:"),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),"try {\n    // code potentially throwing exception\n} catch (TheExceptionClass ex) {\n    // code handling the exception\n}\n")),Object(c.b)("p",null,"Can also have multiple catch statements, catching exceptions of different exception classes. They are evaluated top to bottom, so put more specific exception classes first. It is also possible to have a handler that can handle several exception classes."),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),"try {\n    // code potentially throwing exception\n} catch (ExceptionClass1 ex) {\n    // code handling the exception\n} catch (ExceptionClass2 | ExceptionClass3 ex) {\n    // code handling the exception\n}\n")),Object(c.b)("h2",{id:"cleaning-up-using-try-with-resources"},"Cleaning up using try-with-resources"),Object(c.b)("p",null,"Java offer a ",Object(c.b)("em",{parentName:"p"},"try-with-resources")," statement. In this form of ",Object(c.b)("inlineCode",{parentName:"p"},"try"),"statement, you can specify resources that should be closed automatically. The fact that a resource can be closed automatically is indicated by the fact that it implements the ",Object(c.b)("inlineCode",{parentName:"p"},"AutoCloseable")," interface."),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),'public void write(ArrayList<String> lines) throws FileNotFoundException {\n    try(PrintWriter out = new PrintWriter("output.txt")) {\n        for (String line: lines) {\n            this.possiblyGenerateException(line);\n            out.println(line);\n        }\n    }\n}\n')),Object(c.b)("p",null,"When the code exits the try block, either because we finished processing the lines or an exception was thrown inside, the ",Object(c.b)("inlineCode",{parentName:"p"},"PrintWriter")," will be closed automatically. It is also possible to provide multiple resources to a try-with-resources statement. In that case, the order in which they are closed is the reverse of the order in which they were provided."),Object(c.b)("p",null,"A try-with-resources statement can also have catch clauses catching any exceptions occurring in the statement."),Object(c.b)("p",null,"Note: it is possible that closing an ",Object(c.b)("inlineCode",{parentName:"p"},"AutoCloseable")," throws an exception itself!"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"If closing happened after normal execution of the ",Object(c.b)("inlineCode",{parentName:"li"},"try")," block, that exception is passed to the caller"),Object(c.b)("li",{parentName:"ul"},"If closing happened because of an exception happening inside the ",Object(c.b)("inlineCode",{parentName:"li"},"try")," block, the exception from the ",Object(c.b)("inlineCode",{parentName:"li"},"try")," block is passed to the caller and any exceptions generated by subsequently closing the resources will be attached as ",Object(c.b)("em",{parentName:"li"},"suppressed exceptions")," on that exception",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"When catching the exception that happened in the ",Object(c.b)("inlineCode",{parentName:"li"},"try")," block (the ",Object(c.b)("em",{parentName:"li"},"primary exception"),"), you can access those suppressed exceptions by invoking the ",Object(c.b)("inlineCode",{parentName:"li"},"getSuppressed()")," method on the caught exception.")))),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),'public class ThrowsOnClose implements AutoCloseable {\n    @Override\n    public void close() {\n        throw new IllegalStateException("Closing");\n    }\n}\n')),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),'try (ThrowsOnClose throwsOnClose = new ThrowsOnClose()) {\n    throw new IllegalArgumentException("Inside try");\n} catch (Exception e) {\n    System.out.println(e.getMessage()); // Inside try\n\n    for (Throwable suppressed: e.getSuppressed()) {\n        System.out.println(suppressed.getMessage()); // Closing\n    }\n}\n')),Object(c.b)("h2",{id:"cleaning-up-using-finally"},"Cleaning up using ",Object(c.b)("inlineCode",{parentName:"h2"},"finally")),Object(c.b)("p",null,"Alternative to the try-with-resources statement: the ",Object(c.b)("inlineCode",{parentName:"p"},"finally")," clause. "),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"After the ",Object(c.b)("inlineCode",{parentName:"li"},"try")," block and potential ",Object(c.b)("inlineCode",{parentName:"li"},"catch")," blocks, you add a ",Object(c.b)("inlineCode",{parentName:"li"},"finally block")," which will run after the rest of the try-catch statement has finished"),Object(c.b)("li",{parentName:"ul"},"Especially useful if you need to clean up something that is not an ",Object(c.b)("inlineCode",{parentName:"li"},"AutoCloseable"),"."),Object(c.b)("li",{parentName:"ul"},"Note: avoid throwing exceptions in the ",Object(c.b)("inlineCode",{parentName:"li"},"finally")," block!",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"If the code in the ",Object(c.b)("inlineCode",{parentName:"li"},"try")," block throws an exception and then the ",Object(c.b)("inlineCode",{parentName:"li"},"finally")," block throws an exception, the caller of the method will only see the exception from the ",Object(c.b)("inlineCode",{parentName:"li"},"finally")," block. The suppression mechanism we saw above only works with try-with-resources statements.")))),Object(c.b)("h2",{id:"rethrowing-and-chaining"},"Rethrowing and chaining"),Object(c.b)("p",null,"Rethrowing:"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"Catch the exception"),Object(c.b)("li",{parentName:"ul"},"Do something useful with it (for example, logging it)"),Object(c.b)("li",{parentName:"ul"},"Just throw the exception object that you caught")),Object(c.b)("p",null,"Chaining:"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"Catch the exception"),Object(c.b)("li",{parentName:"ul"},"Throw a new exception instead"),Object(c.b)("li",{parentName:"ul"},"Original exception is typically included as the cause for the new exception")),Object(c.b)("p",null,"Chaining example:"),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),"try {\n    // set foreign key to parent in database\n} catch (SQLException ex) {            \n    throw new ParentNotFoundException(ex); // sets ex as cause\n}\n")),Object(c.b)("p",null,"When the caller catches the ",Object(c.b)("inlineCode",{parentName:"p"},"ParentNotFoundException"),", it can find the original exception using the ",Object(c.b)("inlineCode",{parentName:"p"},"getCause()")," method. "),Object(c.b)("p",null,"In this case, ",Object(c.b)("inlineCode",{parentName:"p"},"ParentNotFoundException")," has a constructor which allows passing the cause (this is considered good practice). If an exception class does not allow that, the cause for the exception can be set through the ",Object(c.b)("inlineCode",{parentName:"p"},"initCause()")," method."),Object(c.b)("h2",{id:"dealing-with-nullpointerexception"},"Dealing with ",Object(c.b)("inlineCode",{parentName:"h2"},"NullPointerException")),Object(c.b)("p",null,Object(c.b)("inlineCode",{parentName:"p"},"NullPointerException")," is an unchecked exception indicating a programming error (we called a method on a null reference). The best way of dealing with ",Object(c.b)("inlineCode",{parentName:"p"},"NullPointerException")," is to avoid it."),Object(c.b)("p",null,"You can make failure with a ",Object(c.b)("inlineCode",{parentName:"p"},"NullPointerException")," less likely by using the following set of rules for your code:"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"Don\u2019t return null from methods. Wherever possible, return a special case object (e.g. an empty list, which you can easily obtain from ",Object(c.b)("inlineCode",{parentName:"li"},"Collections.emptyList()"),", or an instance of a dedicated class that was intended for these cases)."),Object(c.b)("li",{parentName:"ul"},"Don\u2019t pass null as a method parameter. "),Object(c.b)("li",{parentName:"ul"},"In some other languages, for example TypeScript, the compiler can actually help you enforce these rules.")),Object(c.b)("p",null,"The ",Object(c.b)("inlineCode",{parentName:"p"},"Objects")," class has some convenient methods for preventing problems with null pointers. These can be used for checking arguments or preventing passing null."),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},Object(c.b)("inlineCode",{parentName:"li"},"Objects.requireNonNull()")," throws a ",Object(c.b)("inlineCode",{parentName:"li"},"NullPointerException")," if the argument is null and returns the argument itself otherwise. This does not prevent the ",Object(c.b)("inlineCode",{parentName:"li"},"NullPointerException")," from being thrown. However, the benefit here is that we throw it where the source of the problem lies (",Object(c.b)("inlineCode",{parentName:"li"},"null")," being passed where it is not allowed) instead of at some later point in the code where we try to invoke a method on a null reference."),Object(c.b)("li",{parentName:"ul"},Object(c.b)("inlineCode",{parentName:"li"},"Objects.requireNonNullElse()")," returns either the first parameter or, if the first parameter is null, it returns the second parameter. It is quite similar to the ",Object(c.b)("inlineCode",{parentName:"li"},"COALESCE"),"function in SQL.")),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),'public static void test(String name, String nickname) {\n    name = Objects.requireNonNull(name);\n    nickname = Objects.requireNonNullElse(nickname, "nick");\n}\n')),Object(c.b)("p",null,"Something else that can help is the ",Object(c.b)("inlineCode",{parentName:"p"},"Optional")," type."),Object(c.b)("h2",{id:"turning-checked-exceptions-into-unchecked-exceptions"},"Turning checked exceptions into unchecked exceptions"),Object(c.b)("p",null,"In some cases, you may find yourself getting a checked exception which you want to pass up the method chain as an unchecked exception (for example because you are overriding a method without a ",Object(c.b)("inlineCode",{parentName:"p"},"throws")," declaration allowing the checked exception)."),Object(c.b)("p",null,"Simplest way to do this: chaining (see above)"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"Catch checked exception"),Object(c.b)("li",{parentName:"ul"},"Throw new unchecked exception with checked exception as the cause")),Object(c.b)("p",null,"More sneaky approach: trick the Java compiler into ignoring checked exceptions. Example implementation (taken from ",Object(c.b)("em",{parentName:"p"},"Core Java SE 9 for the Impatient"),"):"),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),'public class Exceptions {\n    @SuppressWarnings("unchecked")\n    private static <T extends Throwable> \n            void throwAs(Throwable e) throws T {\n        throw (T) e; // erased to (Throwable) e\n    }\n\n    public static <V> V doWork(Callable<V> c) {\n        try {\n            return c.call();\n        } catch (Throwable ex) {\n            Exceptions.<RuntimeException>throwAs(ex);\n            return null;\n        }\n    }\n}\n')),Object(c.b)("p",null,"Now, any checked exceptions thrown inside the ",Object(c.b)("inlineCode",{parentName:"p"},"doWork")," method are ignored by the compiler."),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),'public static void test() {\n    // error: unhandled FileNotFoundException\n    new PrintWriter("output.txt"); \n\n    // ok\n    Exceptions.doWork(() -> new PrintWriter("output.txt"));\n}\n')),Object(c.b)("p",null,"Although this is a pretty cool trick, it is not generally applicable in practice. Not only would it be confusing to catch an ",Object(c.b)("inlineCode",{parentName:"p"},"IOException")," from a method that doesn\u2019t declare it, but the compiler does not even allow you to do it."),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),'public static void invokeTest() {\n    try {\n        test();\n    } catch (IOException ex) {\n        // error: unreachable catch block\n    }\n}\n\npublic static void test() {        \n    Exceptions.doWork(() -> new PrintWriter("output.txt"));\n}\n')),Object(c.b)("p",null,"Some cases where this trick may make sense (although not necessarily good practice):"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"Dealing with \u201cimpossible\u201d exceptions",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"Some methods in the standard library have a ",Object(c.b)("inlineCode",{parentName:"li"},"throws"),"clause declaring checked exceptions, although there are some sets of arguments which are ",Object(c.b)("em",{parentName:"li"},"guaranteed")," to ",Object(c.b)("em",{parentName:"li"},"never")," throw an exception"),Object(c.b)("li",{parentName:"ul"},"If you know that you are passing such a set of arguments, you could use this trick to stop the compiler from bothering you about this impossible exception."))),Object(c.b)("li",{parentName:"ul"},"Creating a ",Object(c.b)("inlineCode",{parentName:"li"},"Runnable")," that can throw a checked exception in its ",Object(c.b)("inlineCode",{parentName:"li"},"run()")," method (which does not declare any checked exceptions)",Object(c.b)("ul",{parentName:"li"},Object(c.b)("li",{parentName:"ul"},"You can define custom error handling behavior for the thread (for both checked and unchecked exceptions) in the thread\u2019s uncaught exception handler")))),Object(c.b)("p",null,"Example of the ",Object(c.b)("inlineCode",{parentName:"p"},"Runnable")," case:"),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),'public class TestRunnable implements Runnable {\n    @Override\n    public void run() {\n        Exceptions.doWork(() -> new PrintWriter("unwritableFile"));\n    }\n}\n')),Object(c.b)("pre",null,Object(c.b)("code",Object(a.a)({parentName:"pre"},{className:"language-java"}),'Thread thread = new Thread(new TestRunnable());\n        \nthread.setUncaughtExceptionHandler(new UncaughtExceptionHandler() {\n    @Override\n    public void uncaughtException(Thread t, Throwable e) {\n        if (e instanceof IOException) {\n            System.out.println("Caught IOException");\n        }\n    }\n});\n\nthread.start(); // Caught IOException\n')),Object(c.b)("h2",{id:"resources"},"Resources"),Object(c.b)("ul",null,Object(c.b)("li",{parentName:"ul"},"Core Java SE 9 for the Impatient (book by Cay S. Horstmann)"),Object(c.b)("li",{parentName:"ul"},"Clean Code (book by Robert C. Martin)"),Object(c.b)("li",{parentName:"ul"},Object(c.b)("a",{href:"https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html",target:"_blank",rel:"nofollow noopener noreferrer"},"Unchecked Exceptions \u2014 The Controversy ",Object(c.b)("svg",{class:"embedded-fa-icon"},Object(c.b)("use",{href:"#external-link-alt"})))),Object(c.b)("li",{parentName:"ul"},Object(c.b)("a",{href:"https://stackoverflow.com/questions/27578/when-to-choose-checked-and-unchecked-exceptions",target:"_blank",rel:"nofollow noopener noreferrer"},"When to choose checked and unchecked exceptions ",Object(c.b)("svg",{class:"embedded-fa-icon"},Object(c.b)("use",{href:"#external-link-alt"})))),Object(c.b)("li",{parentName:"ul"},Object(c.b)("a",{href:"https://projectlombok.org/features/SneakyThrows",target:"_blank",rel:"nofollow noopener noreferrer"},"Project Lombok @SneakyThrows (throwing checked exceptions as unchecked) ",Object(c.b)("svg",{class:"embedded-fa-icon"},Object(c.b)("use",{href:"#external-link-alt"}))))))}b.isMDXComponent=!0},231:function(e,t,n){"use strict";n.d(t,"a",(function(){return p})),n.d(t,"b",(function(){return d}));var a=n(0),i=n.n(a);function c(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function r(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(Object(n),!0).forEach((function(t){c(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function l(e,t){if(null==e)return{};var n,a,i=function(e,t){if(null==e)return{};var n,a,i={},c=Object.keys(e);for(a=0;a<c.length;a++)n=c[a],t.indexOf(n)>=0||(i[n]=e[n]);return i}(e,t);if(Object.getOwnPropertySymbols){var c=Object.getOwnPropertySymbols(e);for(a=0;a<c.length;a++)n=c[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(i[n]=e[n])}return i}var s=i.a.createContext({}),b=function(e){var t=i.a.useContext(s),n=t;return e&&(n="function"==typeof e?e(t):r({},t,{},e)),n},p=function(e){var t=b(e.components);return i.a.createElement(s.Provider,{value:t},e.children)},h={inlineCode:"code",wrapper:function(e){var t=e.children;return i.a.createElement(i.a.Fragment,{},t)}},u=Object(a.forwardRef)((function(e,t){var n=e.components,a=e.mdxType,c=e.originalType,o=e.parentName,s=l(e,["components","mdxType","originalType","parentName"]),p=b(n),u=a,d=p["".concat(o,".").concat(u)]||p[u]||h[u]||c;return n?i.a.createElement(d,r({ref:t},s,{components:n})):i.a.createElement(d,r({ref:t},s))}));function d(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var c=n.length,o=new Array(c);o[0]=u;var r={};for(var l in t)hasOwnProperty.call(t,l)&&(r[l]=t[l]);r.originalType=e,r.mdxType="string"==typeof e?e:a,o[1]=r;for(var s=2;s<c;s++)o[s]=n[s];return i.a.createElement.apply(null,o)}return i.a.createElement.apply(null,n)}u.displayName="MDXCreateElement"}}]);